name: Manual Android Build (may work now)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies and Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk wget zip unzip

        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.0:$PATH

        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;33.0.0"

        wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O /usr/local/bin/apktool
        wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.8.1.jar -O /usr/local/bin/apktool.jar
        chmod +rwx /usr/local/bin/apktool

        echo "Verifing Build Tools:"
        ls -l $ANDROID_HOME/build-tools/33.0.0 || echo "Build Tools not found!"

    - name: Compile project
      run: |
        apktool b . -o cstrike_unsigned.apk
        # apksigner sign --ks my-release-key.jks --ks-key-alias my-key-alias --ks-pass pass:whyareyouhere --key-pass pass:nopee11 --out cstrike_signed.apk cstrike_unsigned.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: cstrike-unsigned-new-apk
        path: cstrike_unsigned-new.apk
